apiVersion: apps/v1
kind: Deployment
metadata:
  name: colourapp
  labels:
    app: colourapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: colourapp
  template:
    metadata:
      labels:
        app: colourapp
    spec:
      containers:
      - name: colourapp
        image: davevans/colourapp:v1.1
        ports:
        - containerPort: 80
        env:
        - name: COLOUR
          value: Blue