apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: colour-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: colour-app
    repoURL: https://public.ecr.aws/j8q5k6b9/colour-app
    targetRevision: 1.0.0
  syncPolicy:
    automated: 
      prune: true