apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: nginx
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 13.2.8
      helm:
        valuesFiles:
        - $values/charts/nginx/values.yaml
    - repoURL: https://github.com/davevans/argocd2.git
      targetRevision: develop
      ref: values
  syncPolicy:
    automated: 
      prune: true